Merge `stylelint-fix` command into `stylelint`. (#12)

diff --git a/commands/web/xb-stylelint b/commands/web/xb-stylelint
--- a/commands/web/xb-stylelint
+++ b/commands/web/xb-stylelint
@@ -2,13 +2,26 @@
 
 ## #ddev-generated
 ## Description: Find errors and enforce conventions with Stylelint.
-## Example: ddev xb-stylelint
+## Usage: xb-stylelint [fix]
+## Example: ddev stylelint      # Find errors.\nddev stylelint fix  # Fix errors where possible.
 ## Aliases: stylelint,css
+## ExecRaw: false
+## Flags: []
+## AutocompleteTerms: ["fix"]
 
 UI_DIR="$DDEV_COMPOSER_ROOT/$DDEV_DOCROOT/modules/contrib/experience_builder/ui"
 cd "$UI_DIR" || exit 1
 
+FIX_OPTION=""
+if [[ $1 == "fix" ]]; then
+  FIX_OPTION="--fix"
+elif [[ -n $1 ]]; then
+  echo "Invalid argument: $1"
+  exit 1
+fi
+
 npx stylelint \
   --config "$DDEV_COMPOSER_ROOT/$DDEV_DOCROOT/core/.stylelintrc.json" \
   --ignore-pattern "dist/**/*" \
-  "$UI_DIR/**/*.css"
+  "$UI_DIR/**/*.css" \
+  $FIX_OPTION
